// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoAna.Models;

#nullable disable

namespace ProjetoAna.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231110191846_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoAna.Models.Cliente", b =>
                {
            
                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.ToTable("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
